# Configure the various base URLs and such here -- see integrations below and secrets.yml for passwords
httpd_port: 16673
base_url: http://10.237.200.135:16673
cgi_base: http://10.237.200.135:16673/cgi-bin
img_base: http://10.237.200.135:16673/telephony/img

log_dir: /svc/yamenu/logs

# Show new mail interaction at login?
use_biff: 0

# this should contain a secrets section with ha_token item if you use hass entities!
@include "secrets.yml"

# integrations, for now just home asisstant
integrations:
  hass:
    ha_url: http://10.237.1.239:8123/api

# Here we include any menus that should be used, wildcards OK *only* in the top level file!!!
@include "menus/info.yml"
@include "menus/main.yml"
@include "menus/dir/*.yml"
@include "menus/hass/*.yml"
@include "menus/radio/*.yml"
